apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    app: demo
spec:
  containers:
  - name: test-pod
    image: alpine
    stdin: true
    tty: true
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - name: test-container
      containerPort: 80
    volumeMounts:
    - name: test-persistent-storage
      mountPath: /var/lib/test
  volumes:
  - name: test-persistent-storage
    persistentVolumeClaim:
      claimName: test-pvc
